export interface IRoutePaths {
    HOME: string;
    DOCUMENTATION: string;
    SOURCE_CODE: string;
    GETTING_STARTED: string;
    GETTING_STARTED_INSTALLATION: string;
    GETTING_STARTED_GENERATOR: string;
    CLASSES_BASE_ENTITY: string;
    CLASSES_ENTITY_STATE: string;
    CLASSES_ENTITY_LIST: string;
    CLASSES_REPOSITORY: string;
    CLASSES_ENTITY_STATE_INTERCEPTOR: string;
    CLASSES_I_CQRS_QUERY_PROVIDER: string;
    CLASSES_I_LIST_ITEM_OUTPUT_CQRS_QUERY_PROVIDER: string;
    CLASSES_BASE_USE_CASE: string;
    CLASSES_COMMAND_USE_CASE: string;
    CLASSES_GET_PAGINATED_RESULTS_USE_CASE: string;
    CLASSES_DAPPPER_CQRS_COMMAND_PROVIDER: string;
    CLASSES_DAPPPER_COMMAND: string;
    CLASSES_INTERFACE_COMMAND: string;    
    CLASSES_INTERFACE_COMMAND_PROVIDER: string;
    CLASSES_DAPPER_CQRS_LIST_ITEM_OUTPUT_QUERY_PROVIDER: string;
    CLASSES_DAPPER_CQRS_QUERY_PROVIDER: string;
    CLASSESDAPPER_TABLE_DEFINITION: string;
    CLASSES_COLUMN_DEFINITION: string;
    CLASSES_BASE_UNIT_OF_WORK: string;
}