import { IRoutePaths } from "./routes.path.interface";

export const routePaths: IRoutePaths = {
    HOME: '/',
    DOCUMENTATION: '/documentation',
    SOURCE_CODE: '/source-code',
    GETTING_STARTED: '/getting-started',
    GETTING_STARTED_INSTALLATION: '/getting-started/installation',
    GETTING_STARTED_GENERATOR:  '/getting-started/generator',
    CLASSES_BASE_ENTITY:  '/base-entity',
    CLASSES_ENTITY_LIST:  '/entity-list',
    CLASSES_ENTITY_STATE:  '/entity-state',
    CLASSES_REPOSITORY:  '/repository',
    CLASSES_ENTITY_STATE_INTERCEPTOR:  '/entity-interceptor',
    CLASSES_I_CQRS_QUERY_PROVIDER: '/queryprovider-interface',
    CLASSES_I_LIST_ITEM_OUTPUT_CQRS_QUERY_PROVIDER: '/listitem-output',
    CLASSES_BASE_USE_CASE:'/base-usecase',
    CLASSES_COMMAND_USE_CASE: '/command-usecase',
    CLASSES_GET_PAGINATED_RESULTS_USE_CASE: '/getpaginated-usecase',
    CLASSES_DAPPPER_CQRS_COMMAND_PROVIDER: '/dapper-commandprovider',
    CLASSES_DAPPPER_COMMAND: '/dapper-command',
    CLASSES_INTERFACE_COMMAND: '/ientity-command',
    CLASSES_INTERFACE_COMMAND_PROVIDER: '/icommand-provider',
    CLASSES_DAPPER_CQRS_LIST_ITEM_OUTPUT_QUERY_PROVIDER: '/dapperlistitem-queryprovider',
    CLASSES_DAPPER_CQRS_QUERY_PROVIDER: '/dapper-queryprovider',
    CLASSESDAPPER_TABLE_DEFINITION: '/dapper-tabledefiniton',
    CLASSES_COLUMN_DEFINITION: '/dapper-columndefinition',
    CLASSES_BASE_UNIT_OF_WORK: '/base-unitofwork',
}